### ISSUE TITLE
Post Rating Improvements

### ISSUE THREAD

**Issue by cipitarcea** [gov-ithub/maisimplu.gov.ro#14]
**Interfata:**

a. Sistemul curent de evaluare a Postului (cu Note de la 1 la 5) va fi inlocuit cu un mecanism de +1/-1 Up Down voting. Deasupra butoanelor se va prezenta scorul agregat al voturilor Scor: VALOARE, din X voturi (pozitiv sau negativ)
b. In dreapta Scorului, va fi adaugata posibilitatea distribuirii propunerii: share on Facebook, Google sau Twitter.
c. in dreapta butoanelor de voting se va adauga un buton de adaugat comentarii

a, b, c prezentate mai sus se vor aplica atat in pagina de detalii a propunerii, cat si in listele de propuneri.

La apasarea butoanelor de voting , utilizatorul este invitat sa se logheze, daca nu este deja logat.
Un UP/DOWN rating va insera o inregistrare in maisiwp_ratings , daca nu exista deja. Daca exista deja un rating al userului logat, pentru postul respectiv, aceasta intrare va fi modificata:
UP: rating_rating = 1
DOWN: rating_rating = -1
rating_timestamp = current date
rating_IP = IP-ul utilizatorului

**migrare date:**

update taguri in maisiwp_postmeta:
'ratings_score' = numarul de ratinguri cu valoarea 4 sau 5 - numarul de ratinguri cu valoarea 1 sau 2 din tabela maisiwp_ratings, pentru acelasi post_id 
intrarile unde meta_key = 'ratings_average' se vor sterge
valoarea 'ratings_users' ramane neschimbata

update ratinguri in tabela maisiwp_ratings:
rating_rating = 1 where rating_rating = 4 sau 5
rating_rating = -1 where rating_rating = 4 sau 5
rating_rating = 0 where rating_rating = 3

**Comment by zauan** [comment]
Nu prea imi dau seama de o chestie... ca sa votezi va trebui sa fi logat sau permitem si voturi anonime ( doar pe baza IP-ului ) ?

Din ce am vazut, sistemul vechi nu te forta sa fi logat. Singura metoda de validare era doar pe baza de cookie + IP.

**Comment by cipitarcea** [comment]
intr-o prima varianta o sa incercam sa fortam userii sa se logheze/creeze cont pentru a vota. Scopul este de a putea notifica clientii interesati de o propunere (cei cu voturi UP) in momentul in care propunerea este trimisa spre institutie, sau cand exista o Simplificare procedurala legata de propunere.

**Comment by alexchiraples** [comment]
Eu in paralel, justific la minister. E o schimbare de compotament. Ca si argumente:
- IP si cookie nu e secure. proxy sau ip dinamic iti permit sa "trisezi" la numarul de voturi, manual sau automat (ii avantajeaza pe cei care fac lobby)
- vrem sa ii notificam pe cei care au votat up: cand se trimite catre o institutie, cand se realizeaza o simplificare procedurala

Mai sunt alte argumente?

**Comment by zauan** [comment]
TODO : 
- [ ] Add social share buttons
- [ ] Add rate buttons & functionality
- [ ] Make migration script

**Comment by alexchiraples** [comment]
Avem confirmare de la Dialog Civic si Comisia de taiat hartii sa punem autentificare la sistemul de voturi.

**Comment by zauan** [comment]
http://screenshot.co/#!/16a8b223c7
