### ISSUE TITLE
Add migration.md

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/maisimplu.gov.ro#17]
Production code version: 1.0
Adaugare pasi pentru production 1.1

- [ ] Fisierul ar trebui sa stea in root. Il mutam intr-o faza ulterioara
- [ ] Specificati pasii necesari pentru upgrade productie de la versiunea 1.0 la versiunea 1.1

**Comment by zauan** [comment]
Pasii necesari actuali : 
- se activeaza tema mai-simplu
