### ISSUE TITLE
[QA] PHP error - creeaza cont

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/maisimplu.gov.ro#21]
http://193.230.8.57:8080/inregistrare/

![2016-11-21 12_50_21-creeaza cont](https://cloud.githubusercontent.com/assets/22675415/20479980/2691c70e-afe9-11e6-8476-a72839eb48ce.png)

**Comment by zauan** [comment]
din pacate nu tine de noi... trebuie verificat daca acel plugin are update

**Comment by alexchiraples** [comment]
Ce am putea face macar sa il ascundem, asa cum e in productie?
http://maisimplu.gov.ro/inregistrare/

**Comment by zauan** [comment]
setam display_errors pe off in php :
http://php.net/manual/ro/errorfunc.configuration.php#ini.display-errors

**Comment by tudor-rusu** [comment]
incerc eu sa il rezolv
lucreaza cineva pe erorarea asta?

**Comment by tudor-rusu** [comment]
@zauan setam display_errors pe off in php :
http://php.net/manual/ro/errorfunc.configuration.php#ini.display-errors

e ok, dar cred ca pot rezolva bug-ul fara sa afectam ini

**Comment by alexchiraples** [comment]
@tudor-rusu, te-am adaugat la echipa. Te asignezi tu dupa ce dai accept? 
Nu lucreaza nimeni la eroare

**Comment by zauan** [comment]
Eu insist sa nu rezolvam problema si sa incercam intai sa facem update la plugin... din ce am vazut este un update premium. Daca noi rezolvam problema si facem apoi update la plugin se pierd modificarile noastre. Nu exista o metoda de a rezolva eroarea fara sa pierdem modificarile la un update de plugin. Sugerez ca intai sa facem rost de licenta folosita ( sper ca a fost cumparat acest plugin si nu luat "de pe net" :) ). In mod normal developerii de pluginuri fixeaza astfel de erori.

De asemenea, am cautat putin pe net si am gasit ca problema asta ar trebu sa fie rezolvata intr-un update de plugin : https://github.com/scribu/wp-front-end-editor/issues/101

**Comment by tudor-rusu** [comment]
@zauan vazut si agreat opinia ta, dragule
pana atunci am setat null al treilea parametru, in cazul in care nu exista nu returneaza nici un warning
nu cred ca afecteaza functionalitatea plug-in-ului
in orice caz, se poate reveni dupa update

**Comment by zauan** [comment]
Am vazut... nu afecteaza

**Comment by alexchiraples** [comment]
Testat cu flux de inregistrare si login.

**Comment by d3xuu** [comment]
am adaugat fixul la acest bug si in branchul meu. multumesc de commenturi baieti.
