### ISSUE TITLE
[QA] Update WordPress and all plugins

### ISSUE THREAD

**Issue by zauan** [gov-ithub/maisimplu.gov.ro#23]
Ar trebui sa testam pe mediul de QA ca totul functioneaza OK cu update-urile facute la zi. Din ce am observat pe local, pluginul WP User Frontend Pro nu merge updatat, neavand licenta bagata in setari.

**Comment by alexchiraples** [comment]
Propun sa:
- [ ] Facem o lista cu toate plugin-urile ce ar putea fi actualizate
- [ ] punem lista in acest issue
- [ ] facem update pe mediul local si testam local
- [ ] daca totul merge bine, facem procedura de upgrade pentru qa si prod
- [ ] de preferat, cati mai putin pasi la deployment-ul pentru qa/prod
- [ ] testare toate functionalitatile pe mediul de QA

**Comment by d3xuu** [comment]
Lista pluginuri ce port fi actualizate:

Akismet

All In One SEO Pack

Dave's WordPress Live Search

Disqus Comment System

Profile Builder

Query Monitor - inactiv

WP Super Cache - inactiv

WP User Frontend Pro - nu merge updatat dupa cum precizeaza si zauzan mai sus

WP-FB-AutoConnect

**Comment by d3xuu** [comment]
Functionalitati testate dupa update-ul pluginurilor:

- inregistrare -> emailul a fost trimis cu succes

- autentificare -> redirectionare la autentificare/?loggedout=true
 
- creare propunere persoane fizice

- creare de propunere pentru companii

- update propunere

- evaluarea propunerii merge

- search-ul de propuneri merge

- logout pentru utilizatori normali? doar in panoul de wp la care majoritatea utilizatorilor nu o sa stie ca au acces pentru ca nu exista un link direct

**Comment by d3xuu** [comment]
Lista pluginuri actualizate cu succes:

Akismet

All In One SEO Pack

Dave's WordPress Live Search

Disqus Comment System

Profile Builder

Query Monitor - inactiv

WP Super Cache - inactiv

WP-FB-AutoConnect

**Comment by alexchiraples** [comment]
De verificat #21, nu e inclus in acest merge.
