### ISSUE TITLE
sdk.js:89 Uncaught h {message: "invalid version specified", innerError: undefined}

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/maisimplu.gov.ro#24]
Se reproduce pe QA si pe PROD. Putem face noi ceva?
![2016-11-22 10_56_41-inbox - alexandru chiraples ithub gov ro - outlook](https://cloud.githubusercontent.com/assets/22675415/20517137/72e2b6d6-b0a2-11e6-817e-57c0b5521e80.png)

**Comment by zauan** [comment]
Problema vine de la pluginul "WP-FB-AutoConnect".

Se rezolva daca se face update la plugin.
