### ISSUE TITLE
Adauga propunere - Imagine reprezentativa

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/maisimplu.gov.ro#27]
**Interfata**
Sistemul curent pentru adaugarea unei propuneri va permite adaugarea unei imagini reprezentative.

In fereastra propunere/companie/ si propunere/cetateni/ va fi adaugata o sectiune de adaugare imagine, optional, sub sectiunea "Vă rugăm descrieți problema/obstacolul administrativ *".
Sectiunea va contine:
- Text: "O imagine valoreaza cât 1000 de cuvinte. " Ratio 3:2, size 450x300 pixels (adaptat in functie de suportul oferit de sistem)
- Control: Upload Image, extensii: jpg, jpeg, png 

Propunerile vor trece prin procesul de review manual si la acel moment va fi validata poza din punct de vedere continut.

**Resurse**
https://en.support.wordpress.com/featured-images/
http://wordpress.stackexchange.com/questions/71615/how-to-add-assign-or-change-featured-image-in-post-programmatically

**Comment by zauan** [comment]
Pentru image size ar trebui folosit : add_image_size ( https://developer.wordpress.org/reference/functions/add_image_size/ ). De asemenea cred ca putem sa ne folosim de wp media https://codex.wordpress.org/Javascript_Reference/wp.media.

**Comment by zauan** [comment]
Pasi necesari dupa deploy : 
https://monosnap.com/file/8rWLZJnNqpCcq8wuYDzkBjRKeygXd8

Aceiasi pasi trebuiesc facuti si pentru formularul propunere companie
