### ISSUE TITLE
Publicare propunere - notificare pe email persoana ce a initiat propunerea

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/maisimplu.gov.ro#28]
Dupa ce un moderator publica o propunere, se va trimite un mail catre autorul propunerii cu o informare.

De verificat:
https://wordpress.org/plugins/publish-post-email-notification/installation/

sau alt plugin ce indeplineste aceasta functie.

**Comment by zauan** [comment]
Se poate face si manual cu functia wp_mail

**Comment by d3xuu** [comment]
multumesc de confirmare chiar asta aveam in gand :)

**Comment by d3xuu** [comment]
Ca si un mic update la situatie, se pare ca inainte nu se trimitea notificarea odata ce administratorul publica propunerea iar pluginul recomandat de Alex pare ca merge bine. Mai trebuie acum decis ce includem in template-ul pentru emailul catre useri ce posteaza.

**Comment by d3xuu** [comment]
codul html pentru email template:

<style type="text/css">
    
        .emailImage{
            height:auto !important;
            max-width:600px !important;
            width: 100% !important;
        }
    
</style>

<table><tr><td><img src="http://maisimplu.gov.ro/wp-content/uploads/2016/02/300x300.jpg" width="50" /></td><td><h2 style="padding-top:12px">maisimplu.gov.ro</h2></td></tr></table>

<h3>Propunerea [published_post_title] a fost publicata</h3> <p>Vezi online [published_post_link_html] </p>

<div>
<img src="http://maisimplu.gov.ro/wp-content/themes/zerif-lite/images/bg.jpg" class="emailImage">
</div>

**Comment by alexchiraples** [comment]
De remarcat ca plugin-ul trebuie activat dupa deployment.
