### ISSUE TITLE
Ne lipsește form validation la redactarea unei propuneri

### ISSUE THREAD

**Issue by robintel** [gov-ithub/maisimplu.gov.ro#38]
Precum în exemplul atașat, poate ar fi bine să ne asigurăm că anumite reguli sunt păstrate, ca să păstrăm integritatea vizuală și lizibilitatea paginii.

![missing form validation for proposal](https://cloud.githubusercontent.com/assets/3413911/21075362/b0e22ef6-bf18-11e6-8f68-d825b43702c3.png)

**Comment by zauan** [comment]
se poate rezolva cu white space din css

**Comment by robintel** [comment]
Dacă știam CSS, rezolvam deja. 👍
